/*
 * Notification Dialog - View inbox notifications
 */
package ui.common;

import dao.NotificationDAO;
import dao.UserDAO;
import models.User;

import java.util.List;

/**
 * Dialog to view notifications/inbox
 * @author Team
 */
public class NotificationDialog extends javax.swing.JDialog {

    private final User currentUser;
    private final NotificationDAO notificationDAO;
    private final UserDAO userDAO;

    /**
     * Creates new form NotificationDialog
     */
    public NotificationDialog(java.awt.Frame parent, User user) {
        super(parent, true);
        this.currentUser = user;
        this.notificationDAO = new NotificationDAO();
        this.userDAO = new UserDAO();
        initComponents();
        setTitle("Inbox - " + user.getUsername());
        loadNotifications();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        scrollNotifications = new javax.swing.JScrollPane();
        listNotifications = new javax.swing.JList<>();
        btnMarkRead = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inbox");
        setModal(true);

        headerPanel.setBackground(new java.awt.Color(70, 130, 180));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setText("📬 Notifications");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listNotifications.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        scrollNotifications.setViewportView(listNotifications);

        btnMarkRead.setBackground(new java.awt.Color(70, 130, 180));
        btnMarkRead.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMarkRead.setForeground(new java.awt.Color(255, 255, 255));
        btnMarkRead.setText("✅ Mark all as read");
        btnMarkRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkReadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollNotifications, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMarkRead, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(scrollNotifications, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMarkRead, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarkReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkReadActionPerformed
        notificationDAO.markAllAsRead(currentUser.getId());
        javax.swing.JOptionPane.showMessageDialog(this, "All marked as read!");
        dispose();
    }//GEN-LAST:event_btnMarkReadActionPerformed

    private void loadNotifications() {
        javax.swing.DefaultListModel<String> model = new javax.swing.DefaultListModel<>();
        
        List<String> rawNotifs = notificationDAO.getNotificationsRaw(currentUser.getId());

        if (rawNotifs.isEmpty()) {
            model.addElement("📭 No notifications.");
        } else {
            for (int i = rawNotifs.size() - 1; i >= 0; i--) {
                String line = rawNotifs.get(i);
                String[] parts = line.split(";");
                // parts: 0=Receiver, 1=Sender, 2=Msg, 3=IsRead
                
                if (parts.length >= 4) {
                    String senderId = parts[1];
                    User sender = userDAO.findById(Integer.parseInt(senderId));
                    String senderName = (sender != null) ? sender.getUsername() : "Unknown";
                    
                    String msg = parts[2];
                    boolean isRead = Boolean.parseBoolean(parts[3]);
                    
                    String icon = isRead ? "📖 " : "📬 ";
                    model.addElement(icon + "From " + senderName + ": " + msg);
                }
            }
        }
        
        listNotifications.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMarkRead;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JList<String> listNotifications;
    private javax.swing.JScrollPane scrollNotifications;
    // End of variables declaration//GEN-END:variables
}
