/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.admin;

import dao.UserDAO;
import enums.Role;
import ui.common.*;
import dao.*;
import models.*;
import  java.util.*;
/**
 * Admin Dashboard - Main screen for administrators
 * @author Team
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel2 = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        lblWelcome2 = new javax.swing.JLabel();
        btnLogout2 = new javax.swing.JButton();
        mainTabbedPane1 = new javax.swing.JTabbedPane();
        dashboardPanel1 = new javax.swing.JPanel();
        statsPanel1 = new javax.swing.JPanel();
        usersCountPanel1 = new javax.swing.JPanel();
        lblUsersCountTitle1 = new javax.swing.JLabel();
        lblUsersCountValue1 = new javax.swing.JLabel();
        pmCountPanel1 = new javax.swing.JPanel();
        lblPMCountTitle1 = new javax.swing.JLabel();
        lblPMCountValue1 = new javax.swing.JLabel();
        devCountPanel1 = new javax.swing.JPanel();
        lblDevCountTitle1 = new javax.swing.JLabel();
        lblDevCountValue1 = new javax.swing.JLabel();
        testerCountPanel1 = new javax.swing.JPanel();
        lblTesterCountTitle1 = new javax.swing.JLabel();
        lblTesterCountValue1 = new javax.swing.JLabel();
        usersScrollPane1 = new javax.swing.JScrollPane();
        usersTable1 = new javax.swing.JTable();
        usersTopPanel1 = new javax.swing.JPanel();
        lblSearch1 = new javax.swing.JLabel();
        txtSearch1 = new javax.swing.JTextField();
        btnSearch2 = new javax.swing.JButton();
        btnRefresh1 = new javax.swing.JButton();
        usersPanel1 = new javax.swing.JPanel();
        usersTopPanel2 = new javax.swing.JPanel();
        lblSearch2 = new javax.swing.JLabel();
        txtSearch2 = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        btnRefresh2 = new javax.swing.JButton();
        usersScrollPane2 = new javax.swing.JScrollPane();
        usersTable2 = new javax.swing.JTable();
        headerPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        mainTabbedPane = new javax.swing.JTabbedPane();
        dashboardPanel = new javax.swing.JPanel();
        statsPanel = new javax.swing.JPanel();
        usersCountPanel = new javax.swing.JPanel();
        lblUsersCountTitle = new javax.swing.JLabel();
        lblUsersCountValue = new javax.swing.JLabel();
        pmCountPanel = new javax.swing.JPanel();
        lblPMCountTitle = new javax.swing.JLabel();
        lblPMCountValue = new javax.swing.JLabel();
        devCountPanel = new javax.swing.JPanel();
        lblDevCountTitle = new javax.swing.JLabel();
        lblDevCountValue = new javax.swing.JLabel();
        testerCountPanel = new javax.swing.JPanel();
        lblTesterCountTitle = new javax.swing.JLabel();
        lblTesterCountValue = new javax.swing.JLabel();
        activityPanel = new javax.swing.JPanel();
        lblRecentActivity = new javax.swing.JLabel();
        activityScrollPane = new javax.swing.JScrollPane();
        txtActivity = new javax.swing.JTextArea();
        usersPanel = new javax.swing.JPanel();
        usersTopPanel = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        btnEditUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        usersScrollPane = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();

        FormListener formListener = new FormListener();

        headerPanel2.setBackground(new java.awt.Color(0, 102, 102));
        headerPanel2.setPreferredSize(new java.awt.Dimension(1000, 60));

        lblTitle2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("Bug Tracking System - Admin Panel");

        lblWelcome2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWelcome2.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome2.setText("Welcome, Admin");

        btnLogout2.setBackground(new java.awt.Color(220, 53, 69));
        btnLogout2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout2.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout2.setText("Logout");
        btnLogout2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout2.addActionListener(formListener);

        javax.swing.GroupLayout headerPanel2Layout = new javax.swing.GroupLayout(headerPanel2);
        headerPanel2.setLayout(headerPanel2Layout);
        headerPanel2Layout.setHorizontalGroup(
            headerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWelcome2)
                .addGap(18, 18, 18)
                .addComponent(btnLogout2)
                .addGap(20, 20, 20))
        );
        headerPanel2Layout.setVerticalGroup(
            headerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(headerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle2)
                    .addComponent(lblWelcome2)
                    .addComponent(btnLogout2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        mainTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainTabbedPane1.setRequestFocusEnabled(false);

        dashboardPanel1.setBackground(new java.awt.Color(245, 245, 245));

        statsPanel1.setOpaque(false);
        statsPanel1.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        usersCountPanel1.setBackground(new java.awt.Color(0, 123, 255));

        lblUsersCountTitle1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUsersCountTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsersCountTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsersCountTitle1.setText("Total Bugs");

        lblUsersCountValue1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblUsersCountValue1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsersCountValue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsersCountValue1.setText("0");

        javax.swing.GroupLayout usersCountPanel1Layout = new javax.swing.GroupLayout(usersCountPanel1);
        usersCountPanel1.setLayout(usersCountPanel1Layout);
        usersCountPanel1Layout.setHorizontalGroup(
            usersCountPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersCountPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersCountPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsersCountTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsersCountValue1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                .addContainerGap())
        );
        usersCountPanel1Layout.setVerticalGroup(
            usersCountPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersCountPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblUsersCountTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsersCountValue1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        statsPanel1.add(usersCountPanel1);

        pmCountPanel1.setBackground(new java.awt.Color(40, 167, 69));

        lblPMCountTitle1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPMCountTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblPMCountTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPMCountTitle1.setText("Bugs Fixed");

        lblPMCountValue1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblPMCountValue1.setForeground(new java.awt.Color(255, 255, 255));
        lblPMCountValue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPMCountValue1.setText("0");

        javax.swing.GroupLayout pmCountPanel1Layout = new javax.swing.GroupLayout(pmCountPanel1);
        pmCountPanel1.setLayout(pmCountPanel1Layout);
        pmCountPanel1Layout.setHorizontalGroup(
            pmCountPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmCountPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pmCountPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPMCountTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPMCountValue1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                .addContainerGap())
        );
        pmCountPanel1Layout.setVerticalGroup(
            pmCountPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmCountPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblPMCountTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPMCountValue1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        statsPanel1.add(pmCountPanel1);

        devCountPanel1.setBackground(new java.awt.Color(255, 193, 7));

        lblDevCountTitle1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDevCountTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblDevCountTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDevCountTitle1.setText("Bugs Closed");

        lblDevCountValue1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblDevCountValue1.setForeground(new java.awt.Color(255, 255, 255));
        lblDevCountValue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDevCountValue1.setText("0");

        javax.swing.GroupLayout devCountPanel1Layout = new javax.swing.GroupLayout(devCountPanel1);
        devCountPanel1.setLayout(devCountPanel1Layout);
        devCountPanel1Layout.setHorizontalGroup(
            devCountPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devCountPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(devCountPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDevCountTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDevCountValue1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                .addContainerGap())
        );
        devCountPanel1Layout.setVerticalGroup(
            devCountPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devCountPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblDevCountTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDevCountValue1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        statsPanel1.add(devCountPanel1);

        testerCountPanel1.setBackground(new java.awt.Color(220, 53, 69));

        lblTesterCountTitle1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTesterCountTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTesterCountTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTesterCountTitle1.setText("Bugs Opened");

        lblTesterCountValue1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTesterCountValue1.setForeground(new java.awt.Color(255, 255, 255));
        lblTesterCountValue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTesterCountValue1.setText("0");

        javax.swing.GroupLayout testerCountPanel1Layout = new javax.swing.GroupLayout(testerCountPanel1);
        testerCountPanel1.setLayout(testerCountPanel1Layout);
        testerCountPanel1Layout.setHorizontalGroup(
            testerCountPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testerCountPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(testerCountPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTesterCountTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTesterCountValue1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                .addContainerGap())
        );
        testerCountPanel1Layout.setVerticalGroup(
            testerCountPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testerCountPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTesterCountTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTesterCountValue1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        statsPanel1.add(testerCountPanel1);

        usersTable1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        usersTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Full Name", "Username", "Email", "Role", "Created Date", "Updated Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usersTable1.setRowHeight(30);
        usersTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        usersScrollPane1.setViewportView(usersTable1);

        usersTopPanel1.setOpaque(false);

        lblSearch1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSearch1.setText("Search:");

        txtSearch1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch1.setPreferredSize(new java.awt.Dimension(200, 30));

        btnSearch2.setText("Search");
        btnSearch2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch2.addActionListener(formListener);

        btnRefresh1.setText("Refresh");
        btnRefresh1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh1.addActionListener(formListener);

        javax.swing.GroupLayout usersTopPanel1Layout = new javax.swing.GroupLayout(usersTopPanel1);
        usersTopPanel1.setLayout(usersTopPanel1Layout);
        usersTopPanel1Layout.setHorizontalGroup(
            usersTopPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersTopPanel1Layout.createSequentialGroup()
                .addComponent(lblSearch1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 872, Short.MAX_VALUE)
                .addComponent(btnRefresh1))
        );
        usersTopPanel1Layout.setVerticalGroup(
            usersTopPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersTopPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(usersTopPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch1)
                    .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch2)
                    .addComponent(btnRefresh1))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout dashboardPanel1Layout = new javax.swing.GroupLayout(dashboardPanel1);
        dashboardPanel1.setLayout(dashboardPanel1Layout);
        dashboardPanel1Layout.setHorizontalGroup(
            dashboardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(statsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usersScrollPane1)
                .addContainerGap())
            .addGroup(dashboardPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usersTopPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardPanel1Layout.setVerticalGroup(
            dashboardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(statsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usersTopPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usersScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainTabbedPane1.addTab("Dashboard", dashboardPanel1);

        usersPanel1.setBackground(new java.awt.Color(245, 245, 245));

        usersTopPanel2.setOpaque(false);

        lblSearch2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSearch2.setText("Search:");

        txtSearch2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch2.setPreferredSize(new java.awt.Dimension(200, 30));

        btnSearch1.setText("Search");
        btnSearch1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch1.addActionListener(formListener);

        btnRefresh2.setText("Refresh");
        btnRefresh2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh2.addActionListener(formListener);

        javax.swing.GroupLayout usersTopPanel2Layout = new javax.swing.GroupLayout(usersTopPanel2);
        usersTopPanel2.setLayout(usersTopPanel2Layout);
        usersTopPanel2Layout.setHorizontalGroup(
            usersTopPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersTopPanel2Layout.createSequentialGroup()
                .addComponent(lblSearch2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh2))
        );
        usersTopPanel2Layout.setVerticalGroup(
            usersTopPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersTopPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(usersTopPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch2)
                    .addComponent(txtSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch1)
                    .addComponent(btnRefresh2))
                .addGap(10, 10, 10))
        );

        usersTable2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        usersTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Full Name", "Username", "Email", "Role", "Created Date", "Updated Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usersTable2.setRowHeight(30);
        usersTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        usersTable2.addContainerListener(formListener);
        usersScrollPane2.setViewportView(usersTable2);

        javax.swing.GroupLayout usersPanel1Layout = new javax.swing.GroupLayout(usersPanel1);
        usersPanel1.setLayout(usersPanel1Layout);
        usersPanel1Layout.setHorizontalGroup(
            usersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usersScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usersTopPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        usersPanel1Layout.setVerticalGroup(
            usersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(usersTopPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usersScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        mainTabbedPane1.addTab("Manage Users", usersPanel1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard - Bug Tracking System");
        setMinimumSize(new java.awt.Dimension(1000, 700));

        headerPanel.setBackground(new java.awt.Color(0, 102, 102));
        headerPanel.setPreferredSize(new java.awt.Dimension(1000, 60));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Bug Tracking System - Admin Panel");

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Welcome, Admin");

        btnLogout.setBackground(new java.awt.Color(220, 53, 69));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(formListener);

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addGap(20, 20, 20))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(lblWelcome)
                    .addComponent(btnLogout))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        mainTabbedPane.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainTabbedPane.addContainerListener(formListener);

        dashboardPanel.setBackground(new java.awt.Color(245, 245, 245));

        statsPanel.setOpaque(false);
        statsPanel.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        usersCountPanel.setBackground(new java.awt.Color(0, 123, 255));

        lblUsersCountTitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUsersCountTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblUsersCountTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsersCountTitle.setText("Total Users");

        lblUsersCountValue.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblUsersCountValue.setForeground(new java.awt.Color(255, 255, 255));
        lblUsersCountValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsersCountValue.setText("0");

        javax.swing.GroupLayout usersCountPanelLayout = new javax.swing.GroupLayout(usersCountPanel);
        usersCountPanel.setLayout(usersCountPanelLayout);
        usersCountPanelLayout.setHorizontalGroup(
            usersCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersCountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsersCountTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsersCountValue, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addContainerGap())
        );
        usersCountPanelLayout.setVerticalGroup(
            usersCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersCountPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblUsersCountTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsersCountValue)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        statsPanel.add(usersCountPanel);

        pmCountPanel.setBackground(new java.awt.Color(40, 167, 69));

        lblPMCountTitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPMCountTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblPMCountTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPMCountTitle.setText("Project Managers");

        lblPMCountValue.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblPMCountValue.setForeground(new java.awt.Color(255, 255, 255));
        lblPMCountValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPMCountValue.setText("0");

        javax.swing.GroupLayout pmCountPanelLayout = new javax.swing.GroupLayout(pmCountPanel);
        pmCountPanel.setLayout(pmCountPanelLayout);
        pmCountPanelLayout.setHorizontalGroup(
            pmCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmCountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pmCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPMCountTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPMCountValue, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addContainerGap())
        );
        pmCountPanelLayout.setVerticalGroup(
            pmCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmCountPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblPMCountTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPMCountValue)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        statsPanel.add(pmCountPanel);

        devCountPanel.setBackground(new java.awt.Color(255, 193, 7));

        lblDevCountTitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDevCountTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblDevCountTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDevCountTitle.setText("Developers");

        lblDevCountValue.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblDevCountValue.setForeground(new java.awt.Color(255, 255, 255));
        lblDevCountValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDevCountValue.setText("0");

        javax.swing.GroupLayout devCountPanelLayout = new javax.swing.GroupLayout(devCountPanel);
        devCountPanel.setLayout(devCountPanelLayout);
        devCountPanelLayout.setHorizontalGroup(
            devCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devCountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(devCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDevCountTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDevCountValue, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addContainerGap())
        );
        devCountPanelLayout.setVerticalGroup(
            devCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devCountPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblDevCountTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDevCountValue)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        statsPanel.add(devCountPanel);

        testerCountPanel.setBackground(new java.awt.Color(220, 53, 69));

        lblTesterCountTitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTesterCountTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTesterCountTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTesterCountTitle.setText("Testers");

        lblTesterCountValue.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTesterCountValue.setForeground(new java.awt.Color(255, 255, 255));
        lblTesterCountValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTesterCountValue.setText("0");

        javax.swing.GroupLayout testerCountPanelLayout = new javax.swing.GroupLayout(testerCountPanel);
        testerCountPanel.setLayout(testerCountPanelLayout);
        testerCountPanelLayout.setHorizontalGroup(
            testerCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testerCountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(testerCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTesterCountTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTesterCountValue, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addContainerGap())
        );
        testerCountPanelLayout.setVerticalGroup(
            testerCountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testerCountPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTesterCountTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTesterCountValue)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        statsPanel.add(testerCountPanel);

        activityPanel.setBackground(new java.awt.Color(255, 255, 255));
        activityPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblRecentActivity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRecentActivity.setText("Recent Activity");

        txtActivity.setEditable(false);
        txtActivity.setColumns(20);
        txtActivity.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtActivity.setRows(5);
        txtActivity.setText("• System initialized\n• Ready to manage users and bugs\n• No recent activity");
        activityScrollPane.setViewportView(txtActivity);

        javax.swing.GroupLayout activityPanelLayout = new javax.swing.GroupLayout(activityPanel);
        activityPanel.setLayout(activityPanelLayout);
        activityPanelLayout.setHorizontalGroup(
            activityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblRecentActivity)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(activityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activityScrollPane)
                .addContainerGap())
        );
        activityPanelLayout.setVerticalGroup(
            activityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblRecentActivity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activityScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(statsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(activityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        mainTabbedPane.addTab("Dashboard", dashboardPanel);

        usersPanel.setBackground(new java.awt.Color(245, 245, 245));

        usersTopPanel.setOpaque(false);

        lblSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSearch.setText("Search:");

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setPreferredSize(new java.awt.Dimension(200, 30));

        btnSearch.setText("Search");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(formListener);

        btnAddUser.setBackground(new java.awt.Color(40, 167, 69));
        btnAddUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAddUser.setText("+ Add User");
        btnAddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddUser.addActionListener(formListener);

        btnEditUser.setBackground(new java.awt.Color(0, 123, 255));
        btnEditUser.setForeground(new java.awt.Color(255, 255, 255));
        btnEditUser.setText("Edit");
        btnEditUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditUser.addActionListener(formListener);

        btnDeleteUser.setBackground(new java.awt.Color(220, 53, 69));
        btnDeleteUser.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteUser.setText("Delete");
        btnDeleteUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteUser.addActionListener(formListener);

        btnRefresh.setText("Refresh");
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addActionListener(formListener);

        javax.swing.GroupLayout usersTopPanelLayout = new javax.swing.GroupLayout(usersTopPanel);
        usersTopPanel.setLayout(usersTopPanelLayout);
        usersTopPanelLayout.setHorizontalGroup(
            usersTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersTopPanelLayout.createSequentialGroup()
                .addComponent(lblSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh))
        );
        usersTopPanelLayout.setVerticalGroup(
            usersTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersTopPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(usersTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnAddUser)
                    .addComponent(btnEditUser)
                    .addComponent(btnDeleteUser)
                    .addComponent(btnRefresh))
                .addGap(10, 10, 10))
        );

        usersTable.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Full Name", "Username", "Email", "Role", "Created Date", "Updated Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usersTable.setRowHeight(30);
        usersTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        usersScrollPane.setViewportView(usersTable);

        javax.swing.GroupLayout usersPanelLayout = new javax.swing.GroupLayout(usersPanel);
        usersPanel.setLayout(usersPanelLayout);
        usersPanelLayout.setHorizontalGroup(
            usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
                    .addComponent(usersTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        usersPanelLayout.setVerticalGroup(
            usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(usersTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        mainTabbedPane.addTab("Manage Users", usersPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
            .addComponent(mainTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainTabbedPane))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.ContainerListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == btnLogout) {
                AdminDashboard.this.btnLogoutActionPerformed(evt);
            }
            else if (evt.getSource() == btnSearch) {
                AdminDashboard.this.btnSearchActionPerformed(evt);
            }
            else if (evt.getSource() == btnAddUser) {
                AdminDashboard.this.btnAddUserActionPerformed(evt);
            }
            else if (evt.getSource() == btnEditUser) {
                AdminDashboard.this.btnEditUserActionPerformed(evt);
            }
            else if (evt.getSource() == btnDeleteUser) {
                AdminDashboard.this.btnDeleteUserActionPerformed(evt);
            }
            else if (evt.getSource() == btnRefresh) {
                AdminDashboard.this.btnRefreshActionPerformed(evt);
            }
            else if (evt.getSource() == btnLogout2) {
                AdminDashboard.this.btnLogout2ActionPerformed(evt);
            }
            else if (evt.getSource() == btnSearch2) {
                AdminDashboard.this.btnSearch2ActionPerformed(evt);
            }
            else if (evt.getSource() == btnRefresh1) {
                AdminDashboard.this.btnRefresh1ActionPerformed(evt);
            }
            else if (evt.getSource() == btnSearch1) {
                AdminDashboard.this.btnSearch1ActionPerformed(evt);
            }
            else if (evt.getSource() == btnRefresh2) {
                AdminDashboard.this.btnRefresh2ActionPerformed(evt);
            }
        }

        public void componentAdded(java.awt.event.ContainerEvent evt) {
            if (evt.getSource() == mainTabbedPane) {
                AdminDashboard.this.mainTabbedPaneComponentAdded(evt);
            }
        }

        public void componentRemoved(java.awt.event.ContainerEvent evt) {
            if (evt.getSource() == usersTable2) {
                AdminDashboard.this.usersTable2ComponentRemoved(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // Open Login Form and close Admin Dashboard
            new LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchText = txtSearch.getText().trim();
        
        // If search is empty, show all users
        if (searchText.isEmpty()) {
            updateDashboard( fetchAllUsers());
            return;
        }
        
        // Search and update table
        UserDAO userDAO = new UserDAO();
        List<User> results = userDAO.search(searchText);
        
        if (results.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "No users found matching: " + searchText,
                "Search Results",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        
        updateDashboard(results);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        AddUserForm addUserForm = new AddUserForm(this, true);
        addUserForm.setVisible(true);
        
        // Refresh table if user was added
        if (addUserForm.isUserAdded()) {
            updateDashboard(fetchAllUsers());
        }
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
        int selectedRow = usersTable.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select a user to edit.",
                "No Selection",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Get user ID from selected row
        int userId = Integer.parseInt(usersTable.getValueAt(selectedRow, 0).toString());
        
        // Open EditUserForm dialog with selected user
        EditUserForm editUserForm = new EditUserForm(this, true, userId);
        editUserForm.setVisible(true);
        
        // Refresh table if user was updated
        if (editUserForm.isUserUpdated()) {
            updateDashboard( fetchAllUsers());
        }
    }//GEN-LAST:event_btnEditUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        int selectedRow = usersTable.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select a user to delete.",
                "No Selection",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this user?",
            "Confirm Delete",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            UserDAO userDAO = new UserDAO();
            int userId = Integer.parseInt(usersTable.getValueAt(selectedRow, 0).toString());
            String username = usersTable.getValueAt(selectedRow, 2).toString();

            userDAO.delete(userId);
            
            ((javax.swing.table.DefaultTableModel) usersTable.getModel()).removeRow(selectedRow);
            javax.swing.JOptionPane.showMessageDialog(this, "User with Username : '" + username + "' deleted successfully!");
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Refreshing user list...");
        updateDashboard( fetchAllUsers());
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnLogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout2ActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // Open Login Form and close Admin Dashboard
            new LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogout2ActionPerformed

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefresh1ActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        String searchText = txtSearch.getText().trim();

        // If search is empty, show all users
        if (searchText.isEmpty()) {
            updateDashboard( fetchAllUsers());
            return;
        }

        // Search and update table
        UserDAO userDAO = new UserDAO();
        List<User> results = userDAO.search(searchText);

        if (results.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "No users found matching: " + searchText,
                "Search Results",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

        updateDashboard(results);
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnRefresh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh2ActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Refreshing user list...");
        updateDashboard( fetchAllUsers());
    }//GEN-LAST:event_btnRefresh2ActionPerformed

    private void usersTable2ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_usersTable2ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_usersTable2ComponentRemoved

    private void mainTabbedPaneComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_mainTabbedPaneComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_mainTabbedPaneComponentAdded

    /**
     * Updates the dashboard statistics
     */
    public void updateStats(int totalUsers, int projectManagers, int developers, int testers) {
        lblUsersCountValue.setText(String.valueOf(totalUsers));
        lblPMCountValue.setText(String.valueOf(projectManagers));
        lblDevCountValue.setText(String.valueOf(developers));
        lblTesterCountValue.setText(String.valueOf(testers));
    }

    /**
     * Adds a user to the table
     */
    public void addUserToTable(String id, String fullName, String username, String email, String role, String createdDate , String updatedDate) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) usersTable.getModel();
        model.addRow(new Object[]{id, fullName, username, email, role, createdDate, updatedDate});
    }

    /**
     * Clears all users from the table
     */
    public void clearUsersTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) usersTable.getModel();
        model.setRowCount(0);
    }

    // Dummy method to get logged-in user 
    //this should be replaced with actual authentication logic
    // that will be implemented by abdo
    public static User getLogedInUser() {
        UserDAO userDAO = new UserDAO();
        return userDAO.findById(1); // Dummy user for now
    }
    
    private List<User> fetchAllUsers() {
        UserDAO userDAO = new UserDAO();
        userDAO.refresh();
        return userDAO.findAll();
    }

    private void updateDashboard(List<User> users) {
        clearUsersTable();
        for (User user : users) {
            if (user.getId() != getLogedInUser().getId()) {               
                addUserToTable(
                    String.valueOf(user.getId()),
                    user.getFullName(),
                    user.getUsername(),
                    user.getEmail(),
                    user.getRole().toString(),
                    user.getCreatedAt().toLocalDate().toString(),
                    user.getUpdatedAt().toLocalDate().toString()
                );
            }
        }
    }

    // Dummy method to simulate fetching recent activity from database
    //this should be replaced with actual fetching logic
    // that will be implemented by Belal
    private String getActivityDataFromDB() {
        String activity = "• System initialized\r\n" + //
                        "• Ready to manage users and bugs\r\n" + //
                        "• No recent activity";
        return activity;
    }

    
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            AdminDashboard dashboard = new AdminDashboard();
            UserDAO userDAO = new UserDAO();
            User logedInUser = getLogedInUser();
            
            dashboard.lblWelcome.setText("Welcome, " + logedInUser.getFullName());
            dashboard.txtActivity.setText(dashboard.getActivityDataFromDB());

            // Sample data for testing
            dashboard.updateStats(userDAO.count(), userDAO.countByRole(Role.PROJECT_MANAGER), userDAO.countByRole(Role.DEVELOPER), userDAO.countByRole(Role.TESTER));
            
            dashboard.updateDashboard(dashboard. fetchAllUsers());

            dashboard.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activityPanel;
    private javax.swing.JScrollPane activityScrollPane;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogout2;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JButton btnRefresh2;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JPanel dashboardPanel1;
    private javax.swing.JPanel devCountPanel;
    private javax.swing.JPanel devCountPanel1;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel headerPanel2;
    private javax.swing.JLabel lblDevCountTitle;
    private javax.swing.JLabel lblDevCountTitle1;
    private javax.swing.JLabel lblDevCountValue;
    private javax.swing.JLabel lblDevCountValue1;
    private javax.swing.JLabel lblPMCountTitle;
    private javax.swing.JLabel lblPMCountTitle1;
    private javax.swing.JLabel lblPMCountValue;
    private javax.swing.JLabel lblPMCountValue1;
    private javax.swing.JLabel lblRecentActivity;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSearch1;
    private javax.swing.JLabel lblSearch2;
    private javax.swing.JLabel lblTesterCountTitle;
    private javax.swing.JLabel lblTesterCountTitle1;
    private javax.swing.JLabel lblTesterCountValue;
    private javax.swing.JLabel lblTesterCountValue1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblUsersCountTitle;
    private javax.swing.JLabel lblUsersCountTitle1;
    private javax.swing.JLabel lblUsersCountValue;
    private javax.swing.JLabel lblUsersCountValue1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWelcome2;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JTabbedPane mainTabbedPane1;
    private javax.swing.JPanel pmCountPanel;
    private javax.swing.JPanel pmCountPanel1;
    private javax.swing.JPanel statsPanel;
    private javax.swing.JPanel statsPanel1;
    private javax.swing.JPanel testerCountPanel;
    private javax.swing.JPanel testerCountPanel1;
    private javax.swing.JTextArea txtActivity;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtSearch2;
    private javax.swing.JPanel usersCountPanel;
    private javax.swing.JPanel usersCountPanel1;
    private javax.swing.JPanel usersPanel;
    private javax.swing.JPanel usersPanel1;
    private javax.swing.JScrollPane usersScrollPane;
    private javax.swing.JScrollPane usersScrollPane1;
    private javax.swing.JScrollPane usersScrollPane2;
    private javax.swing.JTable usersTable;
    private javax.swing.JTable usersTable1;
    private javax.swing.JTable usersTable2;
    private javax.swing.JPanel usersTopPanel;
    private javax.swing.JPanel usersTopPanel1;
    private javax.swing.JPanel usersTopPanel2;
    // End of variables declaration//GEN-END:variables
}
