package ui.tester;
/**
 * Report Bug Form - Form to create new bug
 * @author Ammar
 */

// import for Files
import enums.BugPriority;
import enums.BugStatus;
import dao.BugDAO;
import dao.UserDAO;
import services.EmailService;
import models.Bug;
import models.Role;
import models.User;
import java.io.File;
import java.util.List;
import javax.swing.*;

public class ReportBugForm extends javax.swing.JDialog {

    /**
     * Creates new form ReportBugForm
     */
    private File selectedPocFile;
    private boolean bugReported = false;
    private User currentTester;

    public ReportBugForm(java.awt.Frame parent, boolean modal, User tester) {
        super(parent, modal);
        this.currentTester = tester;
        initComponents();
        setLocationRelativeTo(parent);
        loadDevelopers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bugTitleLabel = new javax.swing.JLabel();
        bugDiscriptionLabel = new javax.swing.JLabel();
        bugTitleText = new javax.swing.JTextField();
        bugDescriptionText = new java.awt.TextArea();
        assignBugBtn = new javax.swing.JButton();
        severityList = new javax.swing.JComboBox<>();
        severityLabel = new javax.swing.JLabel();
        developerLabel = new javax.swing.JLabel();
        devList = new javax.swing.JComboBox<>();
        PoCLabel = new javax.swing.JLabel();
        addPoCBtn = new javax.swing.JButton();
        pocFileLabel = new javax.swing.JLabel();

        setTitle("Report New Bug");

        bugTitleLabel.setText("Title");

        bugDiscriptionLabel.setText("Description");

        assignBugBtn.setText("Assign Bug");
        assignBugBtn.addActionListener(this::assignBugBtnActionPerformed);

        severityList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Critical", "High", "Medium", "low", "info" }));

        severityLabel.setText("Severity");

        developerLabel.setText("Developer");

        devList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dev1", "Dev2", "Dev3", "Dev4" }));

        PoCLabel.setText("PoC");

        addPoCBtn.setText("Add PoC");
        addPoCBtn.addActionListener(this::addPoCBtnActionPerformed);

        pocFileLabel.setText("No file selected");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(devList, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bugTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(severityLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bugDiscriptionLabel)
                                .addComponent(PoCLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bugDescriptionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bugTitleText)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(severityList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(developerLabel)
                                .addGap(239, 239, 239))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addPoCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pocFileLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(assignBugBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bugTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bugTitleLabel))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bugDescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bugDiscriptionLabel))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(severityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(severityList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(developerLabel)
                    .addComponent(devList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PoCLabel)
                    .addComponent(addPoCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pocFileLabel))
                .addGap(38, 38, 38)
                .addComponent(assignBugBtn)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assignBugBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBugBtnActionPerformed
        // Assign Bug to developer -> save info on text files, and clear the form
        // list them depending on priorty
        // Validate inputs
        String title = bugTitleText.getText().trim();
        String description = bugDescriptionText.getText().trim();
        
        if (title.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter a bug title.", 
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE);
            bugTitleText.requestFocus();
            return;
        }
        
        if (description.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter a bug description.", 
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE);
            bugDescriptionText.requestFocus();
            return;
        }
        
        if (devList.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, 
                "Please select a developer to assign the bug.", 
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Create new bug
            Bug bug = new Bug();
            bug.setTitle(title);
            bug.setDescription(description);
            
            // Set severity
            String severityStr = (String) severityList.getSelectedItem();
            bug.setPriority(BugPriority.valueOf(severityStr)); //BugSeverityEnum.valueOf(severityStr)
            
            // Set status
            bug.setStatus(BugStatus.OPEN);
            
            // Set reporter (current tester)
            bug.setReporter(currentTester);
            
            // Set assigned developer
            User selectedDeveloper = (User) devList.getSelectedItem();
            bug.setAssignee(selectedDeveloper);
            
            // Set PoC file path if selected
            if (selectedPocFile != null) {
                bug.setPocFilePath(selectedPocFile.getAbsolutePath());
            }
            
            // Save bug to the text file
            BugDAO bugDAO = new BugDAO();
            Bug savedBug = bugDAO.save(bug);
            
            // send email to the assgined developer
            try{
                EmailService email = new EmailService();
                email.sendEmail(selectedDeveloper.getId()+"", currentTester.getId()+"", title,description);
                System.out.println(">>Notification sent to developer: " + selectedDeveloper.getUsername());
            } catch(Exception ex){
                System.err.println(">>Warning: Failed to send notification\n"
                        + "Error: " + ex.getMessage());
            }
            
            
            
            JOptionPane.showMessageDialog(this, 
                "Bug #" + savedBug.getId() + " reported successfully!\n" +
                "Title: " + savedBug.getTitle() + "\n" +
                "Assigned to: " + selectedDeveloper.getFullName() + "\n" +
                "Severity: " + savedBug.getPriority(), 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            
            bugReported = true;
            clearForm();
            this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error reporting bug: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
//            e.printStackTrace();
        }
    }//GEN-LAST:event_assignBugBtnActionPerformed

    private void addPoCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPoCBtnActionPerformed
        openFileChooser();
    }//GEN-LAST:event_addPoCBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PoCLabel;
    private javax.swing.JButton addPoCBtn;
    private javax.swing.JButton assignBugBtn;
    private java.awt.TextArea bugDescriptionText;
    private javax.swing.JLabel bugDiscriptionLabel;
    private javax.swing.JLabel bugTitleLabel;
    private javax.swing.JTextField bugTitleText;
    private javax.swing.JComboBox<User> devList;
    private javax.swing.JLabel developerLabel;
    private javax.swing.JLabel pocFileLabel;
    private javax.swing.JLabel severityLabel;
    private javax.swing.JComboBox<String> severityList;
    // End of variables declaration//GEN-END:variables

    
    // methods
    private void openFileChooser(){
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose Proof of Concept File");
        
        int userSelection = fileChooser.showOpenDialog(this);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            selectedPocFile = fileChooser.getSelectedFile();
            pocFileLabel.setText(selectedPocFile.getName());
            pocFileLabel.setToolTipText(selectedPocFile.getAbsolutePath());
        }
    }

    private void loadDevelopers() {
        UserDAO userDAO = new UserDAO();
        List<User> developers = userDAO.findByRole(Role.DEVELOPER);
        
        DefaultComboBoxModel<User> model = new DefaultComboBoxModel<>();
        
        for (User dev : developers) {
            model.addElement(dev);
        }
        
        devList.setModel(model);
        
        // Set custom renderer to show developer names
        devList.setRenderer(new DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(
                    JList<?> list, Object value, int index, 
                    boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof User) {
                    User user = (User) value;
                    setText(user.getFullName() + " (" + user.getUsername() + ")");
                }
                return this;
            }
        });
        
        if (developers.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "No developers found in the system.\nPlease contact admin to add developers.", 
                "Warning", 
                JOptionPane.WARNING_MESSAGE);
        } else {
            devList.setSelectedIndex(0);
        }
    }
    
    private void clearForm() {
        bugTitleText.setText("");
        bugDescriptionText.setText("");
        severityList.setSelectedIndex(0);
        selectedPocFile = null;
        pocFileLabel.setText("No file selected");
        if (devList.getModel().getSize() > 0) {
            devList.setSelectedIndex(0);
        }
    }
    
    public boolean isBugReported() {
        return bugReported;
    }
}
