/*
 * Bug Details Dialog - View bug details and update status
 */
package ui.developer;

import dao.BugDAO;
import dao.UserDAO;
import enums.BugStatus;
import models.Bug;
import models.User;
import services.EmailService;
import services.SessionManager;

/**
 * Dialog to view bug details and update status
 * @author Team
 */
public class BugDetailsDialog extends javax.swing.JDialog {
    
    private Bug bug;
    private final BugDAO bugDAO;
    private final UserDAO userDAO;

    /**
     * Creates new form BugDetailsDialog
     */
    public BugDetailsDialog(java.awt.Frame parent, Bug bug) {
        super(parent, true);
        this.bug = bug;
        this.bugDAO = new BugDAO();
        this.userDAO = new UserDAO();
        initComponents();
        setTitle("Bug Details - #" + bug.getId());
        loadStatuses();
        loadBugData();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblTitleLabel = new javax.swing.JLabel();
        lblTitleValue = new javax.swing.JLabel();
        lblProjectLabel = new javax.swing.JLabel();
        lblProjectValue = new javax.swing.JLabel();
        lblPriorityLabel = new javax.swing.JLabel();
        lblPriorityValue = new javax.swing.JLabel();
        lblReporterLabel = new javax.swing.JLabel();
        lblReporterValue = new javax.swing.JLabel();
        lblDateLabel = new javax.swing.JLabel();
        lblDateValue = new javax.swing.JLabel();
        lblStatusLabel = new javax.swing.JLabel();
        cboStatus = new javax.swing.JComboBox<>();
        lblDescriptionLabel = new javax.swing.JLabel();
        scrollDescription = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnUpdate = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bug Details");
        setModal(true);

        headerPanel.setBackground(new java.awt.Color(0, 102, 102));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setText("Bug Details");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitleLabel.setText("Title:");

        lblTitleValue.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblTitleValue.setText(" ");

        lblProjectLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProjectLabel.setText("Project:");

        lblProjectValue.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblProjectValue.setText(" ");

        lblPriorityLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPriorityLabel.setText("Priority:");

        lblPriorityValue.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblPriorityValue.setText(" ");

        lblReporterLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblReporterLabel.setText("Reported by:");

        lblReporterValue.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblReporterValue.setText(" ");

        lblDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDateLabel.setText("Date:");

        lblDateValue.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblDateValue.setText(" ");

        lblStatusLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStatusLabel.setText("Status:");

        cboStatus.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDescriptionLabel.setText("Description:");

        txtDescription.setEditable(false);
        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        txtDescription.setWrapStyleWord(true);
        scrollDescription.setViewportView(txtDescription);

        btnUpdate.setBackground(new java.awt.Color(40, 167, 69));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update Status");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitleValue, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProjectLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProjectValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPriorityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPriorityValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblReporterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblReporterValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDateValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDescriptionLabel)
                    .addComponent(scrollDescription)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleLabel)
                    .addComponent(lblTitleValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectLabel)
                    .addComponent(lblProjectValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriorityLabel)
                    .addComponent(lblPriorityValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReporterLabel)
                    .addComponent(lblReporterValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateLabel)
                    .addComponent(lblDateValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusLabel)
                    .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(lblDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateStatus();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void loadStatuses() {
        cboStatus.removeAllItems();
        for (BugStatus status : BugStatus.values()) {
            cboStatus.addItem(status.name());
        }
    }
    
    private void loadBugData() {
        lblTitleValue.setText(bug.getTitle());
        lblProjectValue.setText(bug.getProjectName() != null ? bug.getProjectName() : "N/A");
        lblPriorityValue.setText(bug.getPriority().name());
        
        // Get reporter name
        User reporter = userDAO.findById(bug.getReporterId());
        lblReporterValue.setText(reporter != null ? reporter.getFullName() : "Unknown");
        
        lblDateValue.setText(bug.getCreatedAt() != null ? 
            bug.getCreatedAt().toLocalDate().toString() : "N/A");
        
        cboStatus.setSelectedItem(bug.getStatus().name());
        txtDescription.setText(bug.getDescription());
    }
    
    private void updateStatus() {
        String selectedStatusStr = (String) cboStatus.getSelectedItem();
        BugStatus newStatus = BugStatus.valueOf(selectedStatusStr);
        BugStatus oldStatus = bug.getStatus();
        
        if (newStatus == oldStatus) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Status is unchanged.", 
                "No Change", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        bug.setStatus(newStatus);
        bug.setUpdatedAt(java.time.LocalDateTime.now());
        
        if (bugDAO.update(bug)) {
            // Send email notification if bug is resolved
            if (newStatus == BugStatus.RESOLVED) {
                User currentDev = SessionManager.getInstance().getCurrentUser();
                if (currentDev != null) {
                    EmailService emailService = new EmailService();
                    emailService.sendBugStatusChangeNotification(bug, currentDev.getId());
                }
            }
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Bug status updated to: " + newStatus, 
                "Success", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Failed to update bug status.", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboStatus;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel lblDateLabel;
    private javax.swing.JLabel lblDateValue;
    private javax.swing.JLabel lblDescriptionLabel;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblPriorityLabel;
    private javax.swing.JLabel lblPriorityValue;
    private javax.swing.JLabel lblProjectLabel;
    private javax.swing.JLabel lblProjectValue;
    private javax.swing.JLabel lblReporterLabel;
    private javax.swing.JLabel lblReporterValue;
    private javax.swing.JLabel lblStatusLabel;
    private javax.swing.JLabel lblTitleLabel;
    private javax.swing.JLabel lblTitleValue;
    private javax.swing.JScrollPane scrollDescription;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
